# Generated by Django 5.1.6 on 2025-02-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_picture',
            field=models.ImageField(upload_to='portfolio/static/images/'),
        ),
    ]
