# Generated by Django 5.1.6 on 2025-02-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_about_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('granted_on', models.DateField()),
                ('link', models.UUIDField()),
                ('category', models.CharField(choices=[('IU', 'Indian Utility'), ('ID', 'Indian Design'), ('FD', 'Foreign Design')], max_length=3)),
            ],
        ),
    ]
