# Generated by Django 5.1.6 on 2025-02-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_patents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patents',
            name='link',
            field=models.URLField(max_length=700),
        ),
    ]
