# Generated by Django 5.1.6 on 2025-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_patents_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patents',
            name='granted_on',
            field=models.CharField(help_text='Format: Month YYYY', max_length=10),
        ),
    ]
