# Generated by Django 5.1.6 on 2025-02-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_patents_granted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patents',
            name='granted_on',
            field=models.CharField(max_length=10),
        ),
    ]
