# Generated by Django 5.1.6 on 2025-02-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_patents_granted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_picture',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
